### ISSUE TITLE
Can You Share WTQ Results?

### ISSUE THREAD

**Issue by Leolty** [HKUNLP/Binder#9]
Would it be possible to share the result files (both `gpt-3.5` and `codex` maybe?) for the WTQ dataset (test set)? I'm planning on sampling a few data points for testing and would appreciate having the same subset for a comparison. Thank you.

**Comment by Timothyxxx** [comment]
Sure. I will upload them later on

**Comment by Timothyxxx** [comment]
Hi, Zhoujun and I uploaded them [here](https://drive.google.com/drive/folders/1h0qOb8xDMhzzG4g0Urqnv01ODBpsP0DU?usp=sharing). Since the limited budget, I only have the result on the test set of ChatGPT now. And the result is slightly lower than the Codex we found. Have fun and contact me if you have any further questions!

**Comment by Leolty** [comment]
Thank you for sharing the results. I appreciate the prompt response. :)
